spring:
  jpa:
#    open-in-view: false
    show-sql: true
    properties.hibernate.format_sql: true
  datasource:
    hikari:
      auto-commit: false
    hibernate.ddl-auto: none
    generate-ddl: false

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"
